version: '2'
services:
  db:
    build: ./db
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - 6379:6379    
  node_server:
    build: ./node-postgres-api
    command: "nodemon server.js"
    volumes:
      - ./node-postgres-api/:/app
    ports:
      - "3002:3000"
    links:
      - "db"
      - "redis"
    depends_on:
      - db
      - redis